# Generated by Django 3.1.1 on 2020-10-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_comp', models.CharField(max_length=250)),
                ('fecha_nac', models.DateField()),
                ('correo', models.CharField(max_length=250)),
                ('telefono', models.FloatField()),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('cod_bodega', models.FloatField(primary_key=True, serialize=False)),
                ('capacidad', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bodega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClExterno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_comp', models.CharField(max_length=250)),
                ('fecha_nac', models.DateField()),
                ('pais', models.CharField(max_length=250)),
                ('telefono', models.FloatField()),
                ('direccion', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cl_externo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClInterno',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_comp', models.CharField(max_length=250)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.FloatField()),
                ('correo', models.CharField(max_length=250)),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'cl_interno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_comp', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.FloatField()),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'consultor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoP',
            fields=[
                ('cod_contrato', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_termino_contrato', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
            ],
            options={
                'db_table': 'contrato_p',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContratoT',
            fields=[
                ('cod_contrato', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_termino_contrato', models.DateField()),
                ('fecha_inicio_contrato', models.DateField()),
            ],
            options={
                'db_table': 'contrato_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('detalle_factura_id', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('subtotal', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('cod_fact', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('total', models.FloatField()),
                ('registro_pago_id_pago', models.FloatField()),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaT',
            fields=[
                ('cod_ot', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_vehiculo', models.CharField(max_length=250)),
                ('tamano_veh', models.CharField(max_length=259)),
                ('capacidad_carga', models.FloatField()),
                ('refrigeracion', models.FloatField()),
                ('ventilacion', models.FloatField()),
                ('precio_transporte', models.FloatField()),
            ],
            options={
                'db_table': 'oferta_t',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.FloatField(primary_key=True, serialize=False)),
                ('estado_pedido', models.CharField(max_length=10)),
                ('descripcion_pedido', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_prod', models.FloatField(primary_key=True, serialize=False)),
                ('nom_prod', models.CharField(max_length=200)),
                ('fecha_prod', models.DateField()),
                ('foto_prod', models.BinaryField(blank=True, null=True)),
                ('origen_prod', models.DateField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=250)),
                ('fecha_nac', models.DateField()),
                ('correo', models.CharField(max_length=250)),
                ('telefono', models.FloatField()),
                ('direccion', models.CharField(max_length=250)),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id_pago', models.FloatField(primary_key=True, serialize=False)),
                ('total', models.FloatField()),
                ('cod_fact', models.FloatField()),
            ],
            options={
                'db_table': 'registro_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroProcesosAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'registro_procesos_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroProcesoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'registro_proceso_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('cod_reporte', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('factura_cod_fact', models.FloatField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('cod_subasta', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_subasta', models.DateField()),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad_prod', models.FloatField()),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre_comp', models.CharField(max_length=250)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.FloatField()),
                ('correo', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('patente_vehiculo', models.CharField(max_length=250)),
                ('tipo_licencia', models.CharField(max_length=250)),
                ('descripcion_vehiculo', models.CharField(max_length=250)),
                ('auth_user_username', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'transportista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
