# Generated by Django 3.1.1 on 2020-10-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreferia', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad_total', models.FloatField()),
                ('precio_total', models.FloatField()),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
    ]
